name: Atualizar GEX

on:
  schedule:
    - cron: '*/30 13-22 * * 1-5'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependÃªncias
        run: pip install requests

      - name: Rodar script
        run: python update.py

      - name: Commit resultado
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@email.com"
          git add .
          git commit -m "Atualizando GEX" || exit 0
          git push
